### ISSUE TITLE
Skipping  SCAM components  and undeclared components

### ISSUE THREAD

**Issue by hm2075** [rainerhahnekamp/sam4sc#13]
The tool report 17 SCAM components

Skipping 17 SCAM component(s):

but I havent set any components as SCAM components yet

also  I get skipping 19 undeclared components but these components are in modules

**Comment by rainerhahnekamp** [comment]
1. An NgModule is already a SCAM when its declarations property has only one element. Can you please verify or provide me with a code snippet?
2. About these undeclared components: Are the NgModules that declare them in another project/folder structure?

**Comment by hm2075** [comment]
i figured this one out,  

its because the component has things after the import statements

e.g

```
import { IPositionQuery } from '../user-access/interfaces/user-access.interface';

export interface AppAccessLevels {
    core: boolean;
    tracker: boolean;
    edischarge: boolean;
    ereferrals: boolean;
    patientFlow: boolean;
}

const APP_ACCESS_LEVELS: AppAccessLevels[] = [
    { core: false, tracker: false, edischarge: false, ereferrals: false, patientFlow: false },
];

@Component({
    selector: 'application-access',
    template: `
 ```
 
 moving this exports and const's to the end of the file or to another file will probably resolve those issues

**Comment by hm2075** [comment]
for 
1. yes,   that makes sense,  can confirm the 17 SCAM components reported are as you say,   one element in declaration property


2. The 19 undeclared component was interesting,  for some it was legacy code so deleted those components,  

others were base classes

e.g
/src/app/modules/inpatient/tracker/tracker-record-forms/templates/classes/form-service.ts: FormServiceClass
which is used by components calling  export class OnCallTasksService
    extends FormServiceClass

not sure how we exclude these from the reporting,   maybe dont need to do anything here but could cause confusion


an interesting edge case was when you have two modules named the same,   had to rename those

**Comment by rainerhahnekamp** [comment]
I will add a comment in the README for clarification. If people are still confused, we can add more explanations later.
