### ISSUE TITLE
incorrect path on npm

### ISSUE THREAD

**Issue by hm2075** [rainerhahnekamp/sam4sc#6]
![image](https://user-images.githubusercontent.com/53794682/160200789-24cc4b4c-60aa-452c-b90d-3daa55ed9ce9.png)

should have a forward slash instead of @

**Comment by hm2075** [comment]
also

![image](https://user-images.githubusercontent.com/53794682/160414500-f9fdbf05-236d-4e0d-8577-2726430eb74e.png)

should be 4sc

**Comment by rainerhahnekamp** [comment]
@all-contributors please add @hm2075  for bug
